version: "3.8"

services:
  web:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - CONFIG_PATH=/app/config.json
